version: "3"
services:
   vendor-portal:  
    image: manodock01/selenium
    environment:
    - BROWSER=chrome
    - HUB_HOST=hub
    - TEST_SUITE=vendor-portal.xml
    volumes:
    - D:\DockWorkspace\06-jenkins-ci-cd\10-runner-approach-1\output\vedor-portal:/home/selenium-docker/test-output
